name: instagramm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0


  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/profile.png
    - images/profile1.png
    - images/profile2.png
    - images/profile3.png
    - images/profile4.png
    - images/profile5.png
    - images/profile6.png
    - images/profile7.png   
    - images/post.png
    - images/post1.png
    - images/post2.jpeg
    - images/post3.jpeg
    - images/post4.jpeg
    - images/post5.jpeg
    - images/post6.jpeg
    - images/post7.jpeg   
    - images/story.png
    



